/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Database.CloseTabButton;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author nguyen van cuong
 */
public class center extends javax.swing.JFrame {

    /**
     * Creates new form List
     */
    public center() {
        initComponents();
         new CloseTabButton(tab,0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        ptree = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel6 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        tab = new javax.swing.JTabbedPane();
        center = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src/image/koala.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }  };
            ToolBar = new javax.swing.JToolBar();
            jPanel4 = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            Label6 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            Menu = new javax.swing.JMenuBar();
            Menu_QuanLy = new javax.swing.JMenu();
            Menu_DanhSachLop = new javax.swing.JMenuItem();
            Menu_HSDatCoc = new javax.swing.JMenuItem();
            DongPhi = new javax.swing.JMenu();
            Menu_HSHoanThanh = new javax.swing.JMenuItem();
            Menu_HSChuaHoanThanh = new javax.swing.JMenuItem();
            HeThong = new javax.swing.JMenu();
            jSeparator1 = new javax.swing.JPopupMenu.Separator();
            Menu_TaiKhoan = new javax.swing.JMenu();
            Menu_ThemTaiKhoan = new javax.swing.JMenuItem();
            Menu_SuaTaiKhoan = new javax.swing.JMenuItem();
            jMenuItem10 = new javax.swing.JMenuItem();
            Menu_Update = new javax.swing.JMenuItem();
            Menu_DangXuat = new javax.swing.JMenuItem();
            Menu_thoat = new javax.swing.JMenuItem();
            jMenu2 = new javax.swing.JMenu();
            Menu_DongBo = new javax.swing.JMenuItem();
            Menu_BackUp = new javax.swing.JMenuItem();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jSplitPane2.setOneTouchExpandable(true);

            jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Koala House");
            javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Koala House Bà Triệu");
            javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("NẮNG MAI (SUNSHINE)");
            javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("SUNSHINE_1");
            treeNode3.add(treeNode4);
            treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("SUNSHINE_2");
            treeNode3.add(treeNode4);
            treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("SUNSHINE_3");
            treeNode3.add(treeNode4);
            treeNode2.add(treeNode3);
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("TỔ ONG (BEEHIVE)");
            treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("BEEHIVE_1");
            treeNode3.add(treeNode4);
            treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("BEEHIVE_2");
            treeNode3.add(treeNode4);
            treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("BEEHIVE_3");
            treeNode3.add(treeNode4);
            treeNode2.add(treeNode3);
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("TỔ KÉN (CHRYSALIS)");
            treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("CHRYSALIS_1");
            treeNode3.add(treeNode4);
            treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("CHRYSALIS_2");
            treeNode3.add(treeNode4);
            treeNode2.add(treeNode3);
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("MẪU GIÁO (KINDERGARTEN)");
            treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("KINDERGARTEN_1");
            treeNode3.add(treeNode4);
            treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("KINDERGARTEN_2");
            treeNode3.add(treeNode4);
            treeNode2.add(treeNode3);
            treeNode1.add(treeNode2);
            treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Koala House Hoàng Ngân");
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("NẮNG MAI (SUNSHINE)");
            treeNode2.add(treeNode3);
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("TỔ ONG (BEEHIVE)");
            treeNode2.add(treeNode3);
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("TỔ KÉN (CHRYSALIS)");
            treeNode2.add(treeNode3);
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("MẪU GIÁO (KINDERGARTEN)");
            treeNode2.add(treeNode3);
            treeNode1.add(treeNode2);
            treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Koala House Phan Kế Bính");
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("NẮNG MAI (SUNSHINE)");
            treeNode2.add(treeNode3);
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("TỔ ONG (BEEHIVE)");
            treeNode2.add(treeNode3);
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("TỔ KÉN (CHRYSALIS)");
            treeNode2.add(treeNode3);
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("MẪU GIÁO (KINDERGARTEN)");
            treeNode2.add(treeNode3);
            treeNode1.add(treeNode2);
            treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Koala House Nguyễn Huy Tự");
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("NẮNG MAI (SUNSHINE)");
            treeNode2.add(treeNode3);
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("TỔ ONG (BEEHIVE)");
            treeNode2.add(treeNode3);
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("TỔ KÉN (CHRYSALIS)");
            treeNode2.add(treeNode3);
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("MẪU GIÁO (KINDERGARTEN)");
            treeNode2.add(treeNode3);
            treeNode1.add(treeNode2);
            jLabel6.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
            jLabel6.setAutoscrolls(true);
            jLabel6.setMinimumSize(new java.awt.Dimension(100, 80));
            jLabel6.setPreferredSize(new java.awt.Dimension(300, 80));
            jLabel6.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
                public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                    jLabel6ValueChanged(evt);
                }
            });
            jScrollPane1.setViewportView(jLabel6);

            javax.swing.GroupLayout ptreeLayout = new javax.swing.GroupLayout(ptree);
            ptree.setLayout(ptreeLayout);
            ptreeLayout.setHorizontalGroup(
                ptreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
            );
            ptreeLayout.setVerticalGroup(
                ptreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
            );

            jSplitPane2.setLeftComponent(ptree);

            javax.swing.GroupLayout centerLayout = new javax.swing.GroupLayout(center);
            center.setLayout(centerLayout);
            centerLayout.setHorizontalGroup(
                centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 1146, Short.MAX_VALUE)
            );
            centerLayout.setVerticalGroup(
                centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 538, Short.MAX_VALUE)
            );

            tab.addTab("Koala House", center);

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tab)
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tab, javax.swing.GroupLayout.Alignment.TRAILING)
            );

            jSplitPane2.setRightComponent(jPanel1);

            ToolBar.setFloatable(false);
            ToolBar.setRollover(true);

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/List.jpg"))); // NOI18N
            jLabel1.setToolTipText("Danh sach hoc sinh");
            jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel1MouseClicked(evt);
                }
            });

            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Bill.png"))); // NOI18N
            jLabel2.setToolTipText("Danh sach phi");
            jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel2MouseClicked(evt);
                }
            });

            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/DSHS.JPG"))); // NOI18N
            jLabel3.setToolTipText("Danh sach hoc sinh chua dong du phi");
            jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel3MouseClicked(evt);
                }
            });

            Label6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images.jpg"))); // NOI18N
            Label6.setToolTipText("Danh sach lop");
            Label6.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    Label6MouseClicked(evt);
                }
            });

            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/print.png"))); // NOI18N
            jLabel5.setToolTipText("May in");

            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bill2.jpg"))); // NOI18N
            jLabel4.setToolTipText("Hoa don");
            jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel4MouseClicked(evt);
                }
            });

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Label6)
                    .addGap(14, 14, 14)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel4)
                    .addGap(15, 15, 15)
                    .addComponent(jLabel5)
                    .addContainerGap(1051, Short.MAX_VALUE))
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(Label6))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            ToolBar.add(jPanel4);

            Menu_QuanLy.setText("Quản Lý");

            Menu_DanhSachLop.setText("Danh Sách Lớp");
            Menu_DanhSachLop.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Menu_DanhSachLopActionPerformed(evt);
                }
            });
            Menu_QuanLy.add(Menu_DanhSachLop);

            Menu_HSDatCoc.setText("Danh sách học sinh ");
            Menu_HSDatCoc.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Menu_HSDatCocActionPerformed(evt);
                }
            });
            Menu_QuanLy.add(Menu_HSDatCoc);

            Menu.add(Menu_QuanLy);

            DongPhi.setText("Quá trình đóng phí");

            Menu_HSHoanThanh.setText("Học sinh đã hoàn thành phí học tập");
            Menu_HSHoanThanh.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Menu_HSHoanThanhActionPerformed(evt);
                }
            });
            DongPhi.add(Menu_HSHoanThanh);

            Menu_HSChuaHoanThanh.setText("Học sinh chưa hoàn thành phí học tập");
            Menu_HSChuaHoanThanh.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Menu_HSChuaHoanThanhActionPerformed(evt);
                }
            });
            DongPhi.add(Menu_HSChuaHoanThanh);

            Menu.add(DongPhi);

            HeThong.setText("Hệ Thống");
            HeThong.add(jSeparator1);

            Menu_TaiKhoan.setText("Tài khoản");

            Menu_ThemTaiKhoan.setText("Thêm");
            Menu_ThemTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Menu_ThemTaiKhoanActionPerformed(evt);
                }
            });
            Menu_TaiKhoan.add(Menu_ThemTaiKhoan);

            Menu_SuaTaiKhoan.setText("Sửa");
            Menu_SuaTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Menu_SuaTaiKhoanActionPerformed(evt);
                }
            });
            Menu_TaiKhoan.add(Menu_SuaTaiKhoan);

            jMenuItem10.setText("Xóa");
            Menu_TaiKhoan.add(jMenuItem10);

            HeThong.add(Menu_TaiKhoan);

            Menu_Update.setText("Cập nhật hệ thống");
            HeThong.add(Menu_Update);

            Menu_DangXuat.setText("Đăng Xuất");
            HeThong.add(Menu_DangXuat);

            Menu_thoat.setText("Thoát");
            HeThong.add(Menu_thoat);

            Menu.add(HeThong);

            jMenu2.setText("Dữ Liệu");

            Menu_DongBo.setText("Đồng Bộ");
            jMenu2.add(Menu_DongBo);

            Menu_BackUp.setText("Backup");
            jMenu2.add(Menu_BackUp);

            Menu.add(jMenu2);

            setJMenuBar(Menu);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSplitPane2)
                .addComponent(ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSplitPane2))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void Menu_HSDatCocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_HSDatCocActionPerformed
        // TODO add your handling code here:
        ListStudent s = new ListStudent();
        s.setName("Danh sach hoc sinh");
        tab.add(s);
        new CloseTabButton(tab,tab.getComponentCount()-2);
        tab.setSelectedComponent(s);   
    
    }//GEN-LAST:event_Menu_HSDatCocActionPerformed

    private void Label6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label6MouseClicked
        // TODO add your handling code here:
        
            ListClasses s = new ListClasses();
            s.setName("Danh sach lop");
            tab.add(s);
            new CloseTabButton(tab,tab.getComponentCount()-2);
            tab.setSelectedComponent(s);
    }//GEN-LAST:event_Label6MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
            ListStudent s = new ListStudent();
            s.setName("Danh sach hoc sinh");
            tab.add(s);
            new CloseTabButton(tab,tab.getComponentCount()-2);
            tab.setSelectedComponent(s);      
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
            ListCost m = new ListCost();
            m.setName("Cac loai hoc phi");
            tab.add(m);
            new CloseTabButton(tab,tab.getComponentCount()-2);
            tab.setSelectedComponent(m);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
            Debt m = new Debt();
            m.setName("Danh sach no");
            tab.add(m);
            new CloseTabButton(tab,tab.getComponentCount()-2);
            tab.setSelectedComponent(m);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
            Receipts m = new Receipts(this,rootPaneCheckingEnabled);
            m.setAlwaysOnTop(rootPaneCheckingEnabled);
            m.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jLabel6ValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode send= (DefaultMutableTreeNode)evt.getPath().getLastPathComponent();
        if(send.isLeaf()&&send.getLevel()==3)
        {
            ListStudentsInClass list= new ListStudentsInClass();
            tab.add(send.toString(), list);
            list.parent = this;
            list.tab = tab;
            new CloseTabButton(tab,tab.getComponentCount()-2);
            tab.setSelectedComponent(list);
        }
    }//GEN-LAST:event_jLabel6ValueChanged

    private void Menu_DanhSachLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_DanhSachLopActionPerformed
        // TODO add your handling code here:
        ListClasses s = new ListClasses();
        s.setName("Danh sach lop");
        tab.add(s);
        new CloseTabButton(tab,tab.getComponentCount()-2);
        tab.setSelectedComponent(s);
    }//GEN-LAST:event_Menu_DanhSachLopActionPerformed

    private void Menu_ThemTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ThemTaiKhoanActionPerformed
        // TODO add your handling code here:
        CreateAcount account = new CreateAcount(this, rootPaneCheckingEnabled);
        account.setAlwaysOnTop(true);
        account.setVisible(true);
    }//GEN-LAST:event_Menu_ThemTaiKhoanActionPerformed

    private void Menu_HSChuaHoanThanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_HSChuaHoanThanhActionPerformed
        // TODO add your handling code here:
        Debt debt = new Debt();
        tab.add("Danh Sach No",debt);
        new CloseTabButton(tab,tab.getComponentCount()-2);
        tab.setSelectedComponent(debt);
    }//GEN-LAST:event_Menu_HSChuaHoanThanhActionPerformed

    private void Menu_HSHoanThanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_HSHoanThanhActionPerformed
        // TODO add your handling code here:
        CompleteFees com = new CompleteFees();
        tab.add("Danh Sach Dong Du Phi",com);
        new CloseTabButton(tab,tab.getComponentCount()-2);
        tab.setSelectedComponent(com);
    }//GEN-LAST:event_Menu_HSHoanThanhActionPerformed

    private void Menu_SuaTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_SuaTaiKhoanActionPerformed
        // TODO add your handling code here:
        CreateAcount c = new CreateAcount(this,rootPaneCheckingEnabled);
        c.setAlwaysOnTop(true);
        c.setTitle();
        c.setButtonOk();
        c.setVisible(true);
    }//GEN-LAST:event_Menu_SuaTaiKhoanActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu DongPhi;
    private javax.swing.JMenu HeThong;
    private javax.swing.JLabel Label6;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem Menu_BackUp;
    private javax.swing.JMenuItem Menu_DangXuat;
    private javax.swing.JMenuItem Menu_DanhSachLop;
    private javax.swing.JMenuItem Menu_DongBo;
    private javax.swing.JMenuItem Menu_HSChuaHoanThanh;
    private javax.swing.JMenuItem Menu_HSDatCoc;
    private javax.swing.JMenuItem Menu_HSHoanThanh;
    private javax.swing.JMenu Menu_QuanLy;
    private javax.swing.JMenuItem Menu_SuaTaiKhoan;
    private javax.swing.JMenu Menu_TaiKhoan;
    private javax.swing.JMenuItem Menu_ThemTaiKhoan;
    private javax.swing.JMenuItem Menu_Update;
    private javax.swing.JMenuItem Menu_thoat;
    private javax.swing.JToolBar ToolBar;
    private javax.swing.JPanel center;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTree jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel ptree;
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
}
